name: Winlator GLIBC Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true

    steps:
    # 1. Checkout repo
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: recursive
        lfs: false

    # 2. Install dependencies
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y wget

    # 3. Setup Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 4. Setup imagefs (MOZE30 ROOTFS)
    - name: Setup imagefs
      run: |
        mkdir -p app/src/main/assets

        # Clean old imagefs (manual, no wildcard)
        rm -f app/src/main/assets/imagefs.txz
        rm -f app/src/main/assets/imagefs.tzst

        echo "Downloading moze30 rootfs (imagefs-ready)..."
        wget --tries=3 --timeout=30 -O app/src/main/assets/imagefs.tzst \
        https://github.com/moze30/rootfs-winlator-glibc/releases/download/rootfs-g7.1.6-1.0/rootfs-g7.1.6-1.0.tzst

        echo "Final assets:"
        ls -lh app/src/main/assets

    # 5. Clean + Build APK
    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew clean assembleDebug --parallel

    # 6. Rename APK
    - name: Rename APK
      run: |
        mv app/build/outputs/apk/debug/app-debug.apk winlator-glibc.apk

    # 7. Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winlator-glibc
        path: winlator-glibc.apk
