name: Winlator GLIBC Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g"

    steps:
    # 1. Checkout repo
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: recursive
        lfs: false

    # 2. Install dependencies
    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y wget unzip

    # 3. Setup Java
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 4. Setup Android SDK + NDK (IMPORTANT FIX)
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK & CMake
      run: |
        sdkmanager "ndk;25.2.9519653" "cmake;3.22.1"

    # 5. Setup imagefs (MOZE30 ROOTFS)
    - name: Setup imagefs
      run: |
        mkdir -p app/src/main/assets

        rm -f app/src/main/assets/imagefs.txz
        rm -f app/src/main/assets/imagefs.tzst

        echo "Downloading rootfs..."
        wget --tries=3 --timeout=30 -O app/src/main/assets/imagefs.tzst \
        https://github.com/moze30/rootfs-winlator-glibc/releases/download/rootfs-g7.1.6-1.0/rootfs-g7.1.6-1.0.tzst

        ls -lh app/src/main/assets

    # 6. Build Debug APK
    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew clean assembleDebug --no-daemon --stacktrace

    # 7. Rename APK
    - name: Rename APK
      run: |
        mv app/build/outputs/apk/debug/app-debug.apk winlator-glibc-debug.apk

    # 8. Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winlator-glibc-debug
        path: winlator-glibc-debug.apk
